package com.sz.dev.db.dynamo.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

@DynamoDBTable(tableName = "articles")
public class Article {

    @DynamoDBGeneratedUuid( DynamoDBAutoGenerateStrategy.CREATE )
    private String id;
    private String title;

    public Article() {
    }

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    public String getId()
    {
        return id;
    }

    public void setId(String id)
    {
        this.id = id;
    }

    public Article(String title) {
        this.title = title;
    }

    @DynamoDBAttribute
    public String getTitle() {
        return title;
    }


}
