db:
  username: ${username.value:postgres}
  password: rer9Ohdpdb
  driver: PostgresDriver
  url: postgres:5432
  hosts: localhost,127.0.0.1
  pool:
    size: 12
    timeout: 10
  pools:
    - size: 1
      timeout: 1
    - size: 2
      timeout: 2
    - size: 3
      timeout: 3

logging:
  level:
    root: INFO
    #com.sz.dev: INFO
    #org.springframework.jdbc.core: TRACE
  file:
    name: szdev.log
    path: /
spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
    format:
      date: iso
  datasource:
    url: jdbc:postgresql://localhost:5433/sz_dev_db_v1
    username: sz_dev_user
    password: rer9Ohdpdb
    driver-class-name: org.postgresql.Driver
  jpa:
    properties.hibernate:
      batch_size: 50
      fetch_size: 50
      show_sql: false
      format_sql: true
      hbm2ddl.auto: validate
    open-in-view: false
