import type { MetaFunction } from "@remix-run/node";
import PublicPageSkeleton from '~/components/skeletons/public/public-page-skeleton';
import React, { useState } from 'react';
import './about.css';
import { Link } from '@remix-run/react';


export const meta: MetaFunction = () => {
	return [
		{title: "About"},
		{name: "description", content: "Welcome to Remix!"},
	];
};

export default function About() {
	const [imgTextShown, setImgTextShown] = useState(false)


	return (
		<PublicPageSkeleton>
			<div>

				<div className={'grid p-6 py overflow-hidden'}>
					<div className={'flex-center-center flex-column p-6'}>
						<h1>Author</h1>

						<div>
							Hello and welcome! I'm Sergei, a software engineer (<Link to={'/me'}>CV</Link>).
							If you have any questions, suggestions, or if you find a mistake, feel free to <Link to={'/contact'}>reach out to me</Link>.
						</div>

						<div className={'p-3 '}></div>

						<h2>About</h2>

						<p>
							This site was created to immerse you in a wide range of software engineering topics.
						</p>

						<p>
							If you find yourself happy to avoid reading long stories with tons of code, you are in the right place.
						</p>
					</div>

					<div
						className={'about-video-wrap mx-auto'}
						onClick={e => setImgTextShown(true)}
						onMouseLeave={e => setImgTextShown(false)}>
						<video
							className={'about-video'}
							width="400px" loop={true} autoPlay={true} muted
						>
							<source src="/videos/about.mp4" type="video/mp4"/>
						</video>

						{
							imgTextShown && <span
                    className={'flex-center-center w-100 about-video-text'}>
              Yet another picture generated by AI
            </span>
						}
					</div>

				</div>

			</div>
		</PublicPageSkeleton>
	);
}
